# Commit Message Generator Configuration
# Copy this file to config.yaml and customize as needed

# AI model configuration
ai:
  model_name: "gpt-4o-mini"  # or "gpt-3.5-turbo" for faster/cheaper results
  temperature: 0.3  # 0.0 to 2.0, higher is more creative/random
  max_tokens: 500   # Maximum length of the generated message
  top_p: 1.0        # Nucleus sampling parameter (0.0 to 1.0)

# Commit message settings
commit:
  require_ticket: true  # Whether a ticket number is required
  default_commit_type: "IMPROVE"  # Default type if not detected
  default_severity: "MEDIUM"     # Default severity if not detected
  max_line_length: 72            # Wrap commit message at this length

# Custom prompts (optional)
custom_prompts:
  # Custom prompt for feature commits
  FEATURE: |
    You are adding a new feature to the codebase. Focus on:
    - What new functionality was added
    - Why this feature is valuable
    - Any important implementation details

  # Custom prompt for bug fixes
  BUGFIX: |
    You are fixing a bug in the code. Explain:
    - What was the bug/issue
    - How it was fixed
    - Any potential side effects to be aware of

  # Custom prompt for documentation updates
  DOC: |
    You are updating documentation. Focus on:
    - What documentation was added/updated
    - Why the changes were made
    - Any important notes for readers

# Git integration
git:
  # Branch name patterns to extract ticket numbers from
  branch_patterns:
    - "^([A-Z]{2,}-[A-Za-z0-9]+).*$"  # Matches ABC-123-description

  # Ignore files/directories when analyzing changes
  ignore_paths:
    - "*.lock"
    - "package-lock.json"
    - "yarn.lock"
    - "node_modules/**"
    - "__pycache__/**"
    - "*.py[cod]"
    - "*.so"
    - ".DS_Store"
    - "*.swp"
    - "*.swo"
    - "*.egg-info"
    - "dist/**"
    - "build/**"
    - "*.log"
    - "*.tmp"
    - "*.bak"
    - ".venv"
    - "venv"
    - "env"
    - ".env"
    - ".env.*"
    - "*.env"
    - "*.env.*"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "commit_gen.log"  # Leave empty to log to console only
