name: Build and Deploy

on:
  # Only trigger on version tag pushes (e.g., v1.0.0)
  push:
    tags:
      - 'v*'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[dev]'

    - name: Build Python package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        python -m pip install --upgrade pip build
        python -m build --sdist --wheel --outdir dist-pypi/

    - name: Build application
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        make clean-all
        make build

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
        files: |
          dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
        packages-dir: dist-pypi/
        verbose: true
